### ISSUE TITLE
填入Cookie后还是一直Loading,我该怎办👶

### ISSUE THREAD

**Issue by yellowfish621** [Mrxiiaobai/fenbi-tools#1]
![image](https://github.com/user-attachments/assets/81d83cc7-137b-46e0-a485-6d8348d4f438)
![image](https://github.com/user-attachments/assets/37955612-eec0-41d8-80c5-c8c84a75c6eb)

**Comment by Mrxiiaobai** [comment]
看插件是否最新版呢，cookie没设置错的话，应该是没啥问题的

**Comment by yellowfish621** [comment]
> 看插件是否最新版呢，cookie没设置错的话，应该是没啥问题的
v1.0.5
![image](https://github.com/user-attachments/assets/08274626-e9bb-4fcb-ac3d-91ebe5ef7beb)

**Comment by yellowfish621** [comment]
好了 是因为我用的粉笔网页版主页cookie的问题

**Comment by lukechenchn** [comment]
> 好了 是因为我用的粉笔网页版主页cookie的问题

跟你同样的问题，请问你是什么问题，怎么解决的

**Comment by yellowfish621** [comment]
> > 好了 是因为我用的粉笔网页版主页cookie的问题
> 
> 跟你同样的问题，请问你是什么问题，怎么解决的

粉笔官网点击题库 用题库相关api的cookie
![image](https://github.com/user-attachments/assets/d99f3a51-c8b1-49e8-8859-3b27c44db42c)

**Comment by lukechenchn** [comment]
> > > 好了 是因为我用的粉笔网页版主页cookie的问题
> > 
> > 
> > 跟你同样的问题，请问你是什么问题，怎么解决的
> 
> 粉笔官网点击题库 用题库相关api的cookie ![image](https://private-user-images.githubusercontent.com/64340757/390985618-d99f3a51-c8b1-49e8-8859-3b27c44db42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjMyMDIsIm5iZiI6MTczMjg2MjkwMiwicGF0aCI6Ii82NDM0MDc1Ny8zOTA5ODU2MTgtZDk5ZjNhNTEtYzhiMS00OWU4LTg4NTktM2IyN2M0NGRiNDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA2NDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MjE2MTRmZjFlMzc5YjQzZDU4ZmE1NmFhYTk5N2I5MDg1ZDlkOWRjMDcyNDI5MzVhMmQ0MjdiMWNjMDI5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5zM5BYoNg3QEGRldMRY-UY20BZ9VFs6HVDhalnpR08s)

已解决  非常感谢
